name: Terraform Deploy

on:
  push:
    branches: [main]
    paths:
      - '**.tf'
      - '**.tfvars'

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.7.0"
  AWS_REGION: "ap-southeast-1"
  ROLE_ARN: "arn:aws:iam::459185600897:role/iac-lab-github-actions"

jobs:
  terraform-deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -var-file="dev.tfvars" -auto-approve
